gcc google.c -o google
gcc amazon.c -o amazon
gcc aosabook.c -o aosa
gcc wiki.c -o wiki
gcc yahoo.c -o yahoo
gcc comserver.c -o com
gcc orgserver.c -o org
gcc iterative_dns.c -o rootdns
gcc dns_client.c -o dc
